// src/auth/domain/enums/rol.enum.ts

export enum RolEnum {
  ADMINISTRADOR = 'ADMINISTRADOR',
  SOPORTE_INSITU = 'SOPORTE_INSITU',
  SOPORTE_REMOTO = 'SOPORTE_REMOTO',
  CLIENTE_EMPRESA = 'CLIENTE_EMPRESA',
  CLIENTE_SUCURSAL = 'CLIENTE_SUCURSAL',
  CLIENTE_TRABAJADOR = 'CLIENTE_TRABAJADOR',
}